# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the azure-pipelines branch
on:
  push:
    branches:
    - master
env:
  Parameters.RestoreBuildProjects: '**/*.csproj'
  Parameters.UnitTestProjects: '**/*UnitTests/*.csproj'
  BuildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Restore
      run: dotnet restore ${{ env.Parameters.RestoreBuildProjects }}
    - name: Build
      run: dotnet ${{ env.Parameters.RestoreBuildProjects }} --configuration ${{ env.BuildConfiguration }}
    - name: Test
      run: dotnet test ${{ env.Parameters.UnitTestProjects }} --configuration ${{ env.BuildConfiguration }}
    - name: Publish
      run: dotnet publish --configuration ${{ env.BuildConfiguration }} --output "${GITHUB_WORKSPACE}"
    - name: Publish functional tests
      run: dotnet publish **/*FunctionalTest*.csproj --configuration ${{ env.BuildConfiguration }} --output "${GITHUB_WORKSPACE}/FunctionalTests"
    - name: Copy runsettings file
      run: cp '/**/*.runsettings' '${{ env.Build.ArtifactStagingDirectory }}/FunctionalTests'
      shell: bash
    - name: Copy ARM templates
      run: cp 'ArmTemplates/' '${GITHUB_WORKSPACE}'
      shell: bash
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${GITHUB_WORKSPACE}
